const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
const ADD_CATEGORY = 'ADD_CATEGORY';
const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';
const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
const DELETE_CATEGORY = 'DELETE_CATEGORY';

export {
    GET_ALL_CATEGORIES, 
    ADD_CATEGORY, 
    GET_CATEGORY_BY_ID, 
    UPDATE_CATEGORY,
    DELETE_CATEGORY
};