const GET_ALL_CHAPTERS = 'GET_ALL_CHAPTERS';
const ADD_CHAPTER = 'ADD_CHAPTER';
const GET_CHAPTER_BY_ID = 'GET_CHAPTER_BY_ID';
const UPDATE_CHAPTER = 'UPDATE_CHAPTER';
const DELETE_CHAPTER = 'DELETE_CHAPTER';
const GET_CHAPTERS_BY_COURSE_ID = 'GET_CHAPTERS_BY_COURSE_ID';

export {
    GET_ALL_CHAPTERS,
    ADD_CHAPTER,
    GET_CHAPTER_BY_ID,
    UPDATE_CHAPTER,
    DELETE_CHAPTER,
    GET_CHAPTERS_BY_COURSE_ID
}