const ADD_COURSE_TO_COURSE_OF_USER = 'ADD_COURSE_TO_COURSE_OF_USER';
const LOGIN = 'LOGIN';
const GET_USER_BY_ID = 'GET_USER_BY_ID';
const UPDATE_USER = 'UPDATE_USER';

export {
    ADD_COURSE_TO_COURSE_OF_USER,
    LOGIN,
    GET_USER_BY_ID,
    UPDATE_USER
}